name: Deploy Lua documentation

on:
  issue_comment:
    types: [created, edited]

jobs:

  # Deploy Lua documentation
  # -------------------------------------------------- 
  deploy_lua_docs:
    name: Deploy Lua documentation
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test'}}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: ./deploy-lua-docs/go.sum

      - name: Build Dagger program
        working-directory: ./deploy-lua-docs
        run: go build -v ./... -o ./deploy-lua-docs

      - name: Run Dagger program
        working-directory: ./deploy-lua-docs
        run: ./deploy-lua-docs
