name: Deploy Lua documentation

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    branches:
      - main

jobs:

  # Deploy Lua documentation
  # -------------------------------------------------- 
  deploy_lua_docs:
    name: Deploy Lua documentation
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test'}}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
          cache-dependency-path: ./deploy-lua-docs/go.sum

      - name: Build Dagger program
        working-directory: ./deploy-lua-docs
        run: go build -v ./...

      - name: Run Dagger program
        env: # Or as an environment variable
          LUA_DOCS_SRV_SSH_PRIVATEKEY: ${{ secrets.SSH_PRIVATE_KEY_DOCKER_SWARM }}
          LUA_DOCS_SRV_SSH_KNOWNHOSTS: ${{ secrets.LUA_DOCS_SRV_SSH_KNOWNHOSTS }}
        working-directory: ./deploy-lua-docs
        run: ./deploy
